In [1]:
#Consider the below code to answer further questions:

#import numpy as np

#list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

#array_list = np.array(object = list_)

In [1]:
#1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#Ans

#Yes, there is a difference in the data type of the list_ and array_list variables.

#A list is a built-in data type in Python that represents a collection of items. It is an ordered sequence of objects, and its elements can be of different data types.

#An array is a data type that represents a collection of items of the same data type. It is typically used when we need to perform mathematical operations on the elements of the collection.

import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
#2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

#Ans

import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
# Print data type of each element in the list
for element in list_:
    print(type(element))
# Print data type of each element in the NumPy array
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
#3. Considering the following changes in the variable, array_list:

#array_list = np.array(object = list_, dtype = int)

#Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

#Consider the below code to answer further questions:

#import numpy as np

#num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

#num_array = np.array(object = num_list)

#Ans

#Yes, there will be a difference in the data type of the elements present in the original Python list list_ and the resulting NumPy array array_list.

#The original list_ variable contains string objects, while the array_list variable contains integer objects.

#To print the data types of each and every element present in both the variables, list_ and array_list, you can use nested loops to iterate over each element and apply the type() function to it.

import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)
# Print data types of each element in original list
for element in list_:
    print(type(element))
# Print data types of each element in NumPy array
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [5]:
#4. Write a code to find the following characteristics of variable, num_array:

#(i) shape

#(ii) size

#Ans

import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
# Find the shape of the array
print("Shape of num_array:", num_array.shape)
# Find the size of the array
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [6]:
#5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

#[Hint: The size of the array will be 9 and the shape will be (3,3).]

#Ans

import numpy as np
# Create a 3x3 array with zeros only
zeros_array = np.zeros((3, 3))
# Print the zeros array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#6. Create an identity matrix of shape (5,5) using numpy functions?

#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

#Ans

import numpy as np
# Create an identity matrix of shape (5,5)
identity_matrix = np.eye(5)
# Print the identity matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
